/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Domain.ConexionArduino;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class PanelConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form PanelConfiguracion
     */
    private VentanaConfiguracion ventanaConfiguracion;
    private ArrayList<JRadioButton> botones;
    private ConexionArduino conexionArduino;
    private int indiceRadioBotones;

    public PanelConfiguracion(VentanaConfiguracion ventanaConfiguracion) {
        initComponents();
        this.ventanaConfiguracion = ventanaConfiguracion;
        ButtonGroup group = new ButtonGroup();
        group.add(this.jRadioButton1);
        group.add(this.jRadioButton2);
        group.add(this.jRadioButton3);
        this.botones = new ArrayList<>();
        this.botones.add(this.jRadioButton1);
        this.botones.add(this.jRadioButton2);
        this.botones.add(this.jRadioButton3);
        this.conexionArduino = ConexionArduino.conexionSinglenton();
        this.indiceRadioBotones = 0;
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, 500, 500);
        g.setFont(new Font("Arial Black", 1, 15));
        this.AccionBotones();
        g.setColor(Color.red);
        g.drawString("Abajo", 5, 320);
        g.fillOval(5, 350, 50, 50);

        g.setColor(Color.BLUE);
        g.drawString("Arriba", 80, 320);
        g.fillOval(80, 350, 50, 50);

        g.setColor(Color.GREEN);
        g.drawString("Aceptar", 150, 320);
        g.fillOval(150, 350, 50, 50);

        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elija la dificultad:");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Facil");

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Intermedio");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Dificil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(421, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void abrirVentana() {
        Ventana ventana = new Ventana();
        ventana.setVisible(true);
        for (int i = 0; i < this.botones.size(); i++) {
            if (this.botones.get(i).isSelected()) {
                ventana.getPanelActividad().recibirDatos(this.botones.get(i).getText());
            }
        }
        this.ventanaConfiguracion.dispose();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables


    public void AccionBotones() {
        String mensaje = this.conexionArduino.mensaje;
        if (!mensaje.isEmpty()) {
            if (this.conexionArduino.mensaje.contains("8")) {
                if (this.indiceRadioBotones >= 0) {
                    this.indiceRadioBotones++;
                    this.indiceRadioBotones = this.indiceRadioBotones % this.botones.size();
                }

            } else if (this.conexionArduino.mensaje.contains("9")) {
                if (this.indiceRadioBotones >= 0) {
                    this.indiceRadioBotones--;
                    this.indiceRadioBotones = this.indiceRadioBotones % this.botones.size();
                    if (this.indiceRadioBotones < 0) {
                        this.indiceRadioBotones = this.botones.size() - 1;
                    }
                } else {
                    this.indiceRadioBotones++;
                }
            } else if (this.conexionArduino.mensaje.contains("6")) {
                this.abrirVentana();
            }
            this.botones.get(this.indiceRadioBotones).doClick();
            this.conexionArduino.limpiarMensaje();
            this.repaint();
        }
    }
}
